### ISSUE TITLE
Contract falls back to any[], not any.

### ISSUE THREAD

**Issue by randarp** [randarp/typed-contract#1]
I don’t think the fallback is working.  I tried to do this

router.get("/", (req: express.Request, res: express.Response) =>  {
    Contract.In(req).IsNotNull();

```
res.render("index", { title: "Express" });
```

});

Which gives me the error:

Error:(7, 17) TS2345: Argument of type 'Request' is not assignable to parameter of type 'any[]'.
 Property 'length' is missing in type 'Request'.

If TC can’t figure out what it is, it should be falling back to any, not any[].

**Comment by Afischbacher** [comment]
Duly noted.. Will look into tomorrow

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.3.8&pv=5.1.1&source=email_footer_2] On Sun, Apr 10, 2016 at 10:50 PM, Randar Puust < notifications@github.com [notifications@github.com] > wrote:
I don’t think the fallback is working. I tried to do this

router.get("/", (req: express.Request, res: express.Response) => {
Contract.In(req).IsNotNull();

res.render("index", { title: "Express" });


});

Which gives me the error:

Error:(7, 17) TS2345: Argument of type 'Request' is not assignable to parameter of type 'any[]'.
Property 'length' is missing in type 'Request'.

If TC can’t figure out what it is, it should be falling back to any, not any[].

**Comment by Afischbacher** [comment]
Hello Randar, 

Welcome to TypedContract! 

Thank you very much for opening the first TypedContract issue. We appreciate all issues that are received and noted by all TypedContract users. The development team will be addressing the issue in the coming days. 

Sincerely 
The TypedContract Team

**Comment by Afischbacher** [comment]
Hello Randar,

We have just release version 1.1 of TypedContract, and have resolved this issue, thank you for you dedication and time to making TypedContract even better!

Sincerely
The TypedContract Team
