### ISSUE TITLE
typed-contract conflicts with node

### ISSUE THREAD

**Issue by randarp** [randarp/typed-contract#2]
In the typed-contract.d.ts, there is a declaration at the bottom for:

declare var module: any;

If you try and use typed-contract in a node project, you get the following error:

`Error:(122, 13) TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NodeModule', but here has type 'any'.`

The problem is there is already a global module in node.d.ts:

`declare var module: NodeModule;`

So the two are conflicting.

**Comment by Afischbacher** [comment]
Hello Randar,

Thank you very much for opening this issue, it will be resolved very shortly.

Thanks again
Sincerely, 

The TypedContract Team

**Comment by randarp** [comment]
This will work in the 1.2 version which is a UMD module.
