### ISSUE TITLE
Error TS2306: File 'node_modules/typed-contract/typedcontract.d.ts' is not a module

### ISSUE THREAD

**Issue by mrok** [randarp/typed-contract#5]
Hi
I am not sure if it is an issue or more likely my error ;(

**Env:**
windows 7
node: v6.6.0
yarn: 0.18.1
typescript 1.8.10

package.json 
```
{
  "dependencies": {
    "typed-contract": "^1.2.3",
    "typescript": "1.8.10"
  }
}
```

**Problem:**
Typed-contract package cannot be imported by Typescript compiler 

Attempt to "compile" the following code:
> .\node_modules\.bin\tsc hello.ts_
```
/// <reference path="node_modules/typed-contract/typedcontract.d.ts" />
import {contract} from 'typed-contract';

class User {   
   constructor(private name: string, private age: Number) {};
}
const user = new User('mrok', 123);
```
ends with error messages:

> hello.ts(2,24): error TS2306: File 'node_modules/typed-contract/typedcontract.d.ts' is not a module.
> hello.ts(2,24): error TS2656: Exported external package typings file 'node_modules/typed-contract/typedcontract.d.ts' is not a module. Please contact the package author to update the package definition.

Any hint/guideline about solution?
Thanks

**Comment by Afischbacher** [comment]
We are currently investigating the issue and will try to solve your issue as soon as possible

Thank you

typed-contract team

**Comment by Afischbacher** [comment]
Hello @mrok ,

We have looked into your opened issue and have found a solution. It seems that when you are importing our typed-contract module, the import name is incorrect.

`import {contract} from 'typed-contract';`

the name for the module is 

`import {contract} from 'typedcontract';`

Here is a link to our documentation on using our npm module
https://github.com/randarp/typed-contract/wiki/Accessing-typed-contract

We will be resolving this issue with a patch to improve our naming conventions.

Thank you for your patience

typed-contract team

**Comment by mrok** [comment]
Hi @Afischbacher

Thanks for your hard work.
The name was the problem - indeed. Unfortunately not the last one ;(

What Typescript version do you use?

This code:
```
/// <reference path="node_modules/typed-contract/typedcontract.d.ts" />
import {contract} from 'typedcontract';
```
is successfully compiled to
```
"use strict";
/// <reference path="node_modules/typed-contract/typedcontract.d.ts" />
var typedcontract_1 = require('typedcontract');
```
and it results in runtime error
`node hello.js `

> module.js:328
>     throw err;
>     ^
> 
> Error: Cannot find module 'typedcontract'

what is true, because 'typedcontract' cannot be found in node_modules directory
![image](https://cloud.githubusercontent.com/assets/905346/21556958/ea17b3dc-ce25-11e6-887b-1f7a58f022f8.png)

Manual change 
`var typedcontract_1 = require('typed-contract');`
solves the issue.

Please take a look here: https://travis-ci.org/#L152

**Comment by Afischbacher** [comment]
Hello again @mrok,

We will be resolving this issue in the next version of typed-contract. 

Thank you for opening an issue. 

typed-contract team

**Comment by randarp** [comment]
Hello @mrok 

Sorry for taking so long on this.  We actually tried to find an elegant fix for a while and never found one.  Our only choice was to deprecate the old package and create a new one that works with import and npm.      It also gave us a chance to go back and make some naming changes that were bugging me and add some enhancements.

The new package is at:
https://www.npmjs.com/package/typedcontract

You will need to:

1. npm uninstall typed-contract
2. npm install typedcontract --save
3. Update any method calls to be camelCase instead of PascalCase.  Migration guide is here https://github.com/randarp/typed-contract/wiki/Migrating-from-1.x-to-2.x

Thanks again for submitting the bug and apologies again for taking so long.

**Comment by mattbishop** [comment]
Great work!
